menus:
    authenticated:
        main: [narrative, bulk-ui]
        developer: [reske-uber-search, reske-admin, jgi-search]
        help: [about, about-services, contact-kbase, help]
    unauthenticated:
        main: []
        developer: []
        help: [about, contact-kbase, help]
